import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { requireAdmin } from "@/lib/auth/require-admin";
function formatDate(value: string) { return new Intl.DateTimeFormat("es-CL", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
export const dynamic = "force-dynamic";

export default async function ImportsPage() {
  const { supabase } = await requireAdmin();
  const [{ count: pending }, { count: migrated }, { count: ignored }, { count: errors }, { data: runs }] = await Promise.all([supabase.from("legacy_imports").select("id", { count: "exact", head: true }).eq("migration_status", "pending"), supabase.from("legacy_imports").select("id", { count: "exact", head: true }).eq("migration_status", "migrated"), supabase.from("legacy_imports").select("id", { count: "exact", head: true }).eq("migration_status", "ignored"), supabase.from("legacy_imports").select("id", { count: "exact", head: true }).eq("migration_status", "error"), supabase.from("migration_runs").select("id,source_file,source_sha256,started_at,finished_at,status,source_rows,imported_rows,rejected_rows,notes").order("started_at", { ascending: false }).limit(20)]);
  return <AppShell><header className="topbar"><div><h1>Importación desde Access</h1><p>Centro de control para migrar el archivo original sin perder registros ni trazabilidad.</p></div><div className="header-actions"><Link className="button button-secondary" href="/importaciones/revision">Revisar filas legado</Link><span className="badge">Colegio Providencia(1).accdb</span></div></header><section className="stats"><article className="stat-card"><span>Pendientes</span><strong>{pending ?? 0}</strong></article><article className="stat-card"><span>Migrados</span><strong>{migrated ?? 0}</strong></article><article className="stat-card"><span>Ignorados</span><strong>{ignored ?? 0}</strong></article><article className="stat-card"><span>Errores</span><strong>{errors ?? 0}</strong></article></section><section className="panel"><div className="panel-heading"><div><h2>Pipeline de migración</h2><p className="muted">El repositorio incluye exportador de Access para Windows e importador idempotente a Supabase.</p></div><Link className="button button-ghost" href="https://github.com/innova-space-edu/Inventario-Colegio-Providencia/blob/main/docs/ACCESS_MIGRATION.md">Ver guía</Link></div><div className="rule-grid"><article><strong>1. Exportar</strong><span>scripts/export-access.ps1 lee las tablas mediante Microsoft ACE sin modificar el .accdb.</span></article><article><strong>2. Preservar</strong><span>Cada fila se guarda primero en legacy_imports con su payload original.</span></article><article><strong>3. Transformar</strong><span>Las ocho tablas principales se convierten a activos, ubicaciones y detalles especializados.</span></article><article><strong>4. Reconciliar</strong><span>Las filas no convertidas se revisan explícitamente y nunca desaparecen del proceso.</span></article></div></section><section className="panel"><div className="panel-heading"><div><h2>Ejecuciones</h2><p className="muted">Historial de procesos de migración.</p></div></div>{runs?.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Inicio</th><th>Archivo</th><th>Estado</th><th>Fuente</th><th>Importadas</th><th>Rechazadas</th><th>Notas</th></tr></thead><tbody>{runs.map((run) => <tr key={run.id}><td>{formatDate(run.started_at)}</td><td>{run.source_file}</td><td><span className="status-pill">{run.status}</span></td><td>{run.source_rows ?? "—"}</td><td>{run.imported_rows ?? "—"}</td><td>{run.rejected_rows ?? "—"}</td><td>{run.notes || "—"}</td></tr>)}</tbody></table></div> : <div className="empty-state">Todavía no se ha ejecutado una importación. La herramienta ya está versionada y preparada para cargar el export real.</div>}</section></AppShell>;
}
