-- RBAC para Inventario Colegio Providencia.
-- Las tablas app_roles/app_permissions/user_roles ya pueden existir en producción;
-- esta migración es idempotente y convierte el inventario desde admin-only a permisos.

alter table public.profiles alter column role set default 'user';

create table if not exists public.app_roles (
  id uuid primary key default gen_random_uuid(), code text not null unique, name text not null,
  description text, is_system boolean not null default false, active boolean not null default true,
  created_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.app_permissions (
  code text primary key, name text not null, description text, module text not null, created_at timestamptz not null default now()
);
create table if not exists public.role_permissions (
  role_id uuid not null references public.app_roles(id) on delete cascade,
  permission_code text not null references public.app_permissions(code) on delete cascade,
  created_at timestamptz not null default now(), primary key(role_id,permission_code)
);
create table if not exists public.user_roles (
  user_id uuid not null references auth.users(id) on delete cascade,
  role_id uuid not null references public.app_roles(id) on delete cascade,
  assigned_by uuid references auth.users(id), assigned_at timestamptz not null default now(), primary key(user_id,role_id)
);

create index if not exists app_roles_active_idx on public.app_roles(active);
create index if not exists app_permissions_module_idx on public.app_permissions(module);
create index if not exists user_roles_user_idx on public.user_roles(user_id);
create index if not exists user_roles_role_idx on public.user_roles(role_id);
create index if not exists role_permissions_role_idx on public.role_permissions(role_id);

insert into public.app_permissions(code,name,description,module) values
('inventory.view','Ver inventario','Puede consultar los activos.','inventory'),('inventory.create','Crear activos','Puede agregar nuevos activos.','inventory'),('inventory.edit','Editar activos','Puede modificar los activos.','inventory'),('inventory.dispose','Dar de baja','Puede dar activos de baja.','inventory'),('inventory.reactivate','Reactivar activos','Puede reactivar activos dados de baja.','inventory'),('locations.view','Ver ubicaciones','Puede consultar ubicaciones.','locations'),('locations.manage','Administrar ubicaciones','Puede crear y modificar ubicaciones.','locations'),('reports.view','Ver informes','Puede consultar informes.','reports'),('reports.export','Exportar informes','Puede generar CSV y documentos.','reports'),('quality.view','Ver calidad de datos','Puede revisar inconsistencias del inventario.','quality'),('quality.manage','Corregir calidad de datos','Puede corregir inconsistencias detectadas.','quality'),('audit.view','Ver auditoría','Puede consultar el historial de cambios.','audit'),('imports.view','Ver importaciones','Puede consultar procesos de importación.','imports'),('imports.manage','Administrar importaciones','Puede ejecutar y reconciliar migraciones Access.','imports'),('users.view','Ver usuarios','Puede consultar usuarios autorizados.','users'),('users.manage','Administrar usuarios','Puede administrar usuarios de la aplicación.','users'),('users.assign_roles','Asignar roles','Puede asignar y retirar roles.','users'),('roles.view','Ver roles','Puede consultar roles y permisos.','roles'),('roles.create','Crear roles','Puede crear nuevos roles.','roles'),('roles.edit','Editar roles','Puede modificar roles.','roles'),('roles.delete','Eliminar roles','Puede eliminar roles no protegidos.','roles'),('roles.manage_permissions','Administrar permisos','Puede modificar permisos de cada rol.','roles'),('system.view','Ver configuración','Puede consultar la configuración del sistema.','system'),('system.manage','Administrar sistema','Puede modificar la configuración administrativa.','system')
on conflict(code) do update set name=excluded.name,description=excluded.description,module=excluded.module;

insert into public.app_roles(code,name,description,is_system,active) values
('super_admin','Administrador principal','Control total del Inventario Colegio Providencia.',true,true),
('inventory_manager','Encargado de inventario','Puede administrar activos, ubicaciones, bajas e informes.',true,true),
('inventory_operator','Operador de inventario','Puede registrar y actualizar activos.',true,true),
('viewer','Solo lectura','Puede consultar inventario e informes sin modificar datos.',true,true)
on conflict(code) do update set name=excluded.name,description=excluded.description,is_system=excluded.is_system,active=true;

insert into public.role_permissions(role_id,permission_code) select r.id,p.code from public.app_roles r cross join public.app_permissions p where r.code='super_admin' on conflict do nothing;
insert into public.role_permissions(role_id,permission_code) select r.id,p.code from public.app_roles r join public.app_permissions p on p.code in ('inventory.view','inventory.create','inventory.edit','inventory.dispose','inventory.reactivate','locations.view','locations.manage','reports.view','reports.export','quality.view','quality.manage','audit.view') where r.code='inventory_manager' on conflict do nothing;
insert into public.role_permissions(role_id,permission_code) select r.id,p.code from public.app_roles r join public.app_permissions p on p.code in ('inventory.view','inventory.create','inventory.edit','locations.view','reports.view','quality.view') where r.code='inventory_operator' on conflict do nothing;
insert into public.role_permissions(role_id,permission_code) select r.id,p.code from public.app_roles r join public.app_permissions p on p.code in ('inventory.view','locations.view','reports.view') where r.code='viewer' on conflict do nothing;

create or replace function public.is_root_admin() returns boolean language sql stable security invoker set search_path='' as $$
  select exists(select 1 from public.profiles p where p.id=(select auth.uid()) and lower(p.email)=lower('admin@colprovidencia.cl') and p.role='admin' and p.active=true);
$$;
create or replace function public.has_permission(p_permission text) returns boolean language sql stable security invoker set search_path='' as $$
  select public.is_root_admin() or exists(select 1 from public.user_roles ur join public.app_roles r on r.id=ur.role_id join public.role_permissions rp on rp.role_id=r.id where ur.user_id=(select auth.uid()) and r.active=true and rp.permission_code=p_permission);
$$;
revoke execute on function public.is_root_admin() from public,anon;
revoke execute on function public.has_permission(text) from public,anon;
grant execute on function public.is_root_admin() to authenticated;
grant execute on function public.has_permission(text) to authenticated;

alter table public.app_roles enable row level security; alter table public.app_permissions enable row level security; alter table public.role_permissions enable row level security; alter table public.user_roles enable row level security;
revoke all on public.app_roles,public.app_permissions,public.role_permissions,public.user_roles from anon;
grant select,insert,update,delete on public.app_roles to authenticated; grant select on public.app_permissions to authenticated; grant select,insert,update,delete on public.role_permissions to authenticated; grant select,insert,update,delete on public.user_roles to authenticated;

-- RBAC administrativo.
drop policy if exists app_roles_select on public.app_roles; drop policy if exists app_roles_insert on public.app_roles; drop policy if exists app_roles_update on public.app_roles; drop policy if exists app_roles_delete on public.app_roles;
create policy app_roles_select on public.app_roles for select to authenticated using(public.is_root_admin() or public.has_permission('roles.view') or exists(select 1 from public.user_roles ur where ur.user_id=(select auth.uid()) and ur.role_id=app_roles.id));
create policy app_roles_insert on public.app_roles for insert to authenticated with check(public.is_root_admin());
create policy app_roles_update on public.app_roles for update to authenticated using(public.is_root_admin()) with check(public.is_root_admin());
create policy app_roles_delete on public.app_roles for delete to authenticated using(public.is_root_admin() and is_system=false);
drop policy if exists permissions_select on public.app_permissions; create policy permissions_select on public.app_permissions for select to authenticated using(public.is_root_admin() or public.has_permission('roles.view'));
drop policy if exists role_permissions_select on public.role_permissions; drop policy if exists role_permissions_insert on public.role_permissions; drop policy if exists role_permissions_delete on public.role_permissions;
create policy role_permissions_select on public.role_permissions for select to authenticated using(public.is_root_admin() or public.has_permission('roles.view') or exists(select 1 from public.user_roles ur where ur.user_id=(select auth.uid()) and ur.role_id=role_permissions.role_id));
create policy role_permissions_insert on public.role_permissions for insert to authenticated with check(public.is_root_admin()); create policy role_permissions_delete on public.role_permissions for delete to authenticated using(public.is_root_admin());
drop policy if exists user_roles_select on public.user_roles; drop policy if exists user_roles_insert on public.user_roles; drop policy if exists user_roles_update on public.user_roles; drop policy if exists user_roles_delete on public.user_roles;
create policy user_roles_select on public.user_roles for select to authenticated using(user_id=(select auth.uid()) or public.is_root_admin() or public.has_permission('users.view'));
create policy user_roles_insert on public.user_roles for insert to authenticated with check(public.is_root_admin()); create policy user_roles_update on public.user_roles for update to authenticated using(public.is_root_admin()) with check(public.is_root_admin()); create policy user_roles_delete on public.user_roles for delete to authenticated using(public.is_root_admin());

-- Perfil: cada usuario activo puede leerse a sí mismo; root puede administrar.
revoke all on public.profiles from anon; grant select,insert,update on public.profiles to authenticated;
drop policy if exists profiles_select_self_admin on public.profiles; drop policy if exists profiles_select_self_or_root on public.profiles; drop policy if exists profiles_root_insert on public.profiles; drop policy if exists profiles_root_update on public.profiles;
create policy profiles_select_self_or_root on public.profiles for select to authenticated using(id=(select auth.uid()) or public.is_root_admin() or public.has_permission('users.view'));
create policy profiles_root_insert on public.profiles for insert to authenticated with check(public.is_root_admin()); create policy profiles_root_update on public.profiles for update to authenticated using(public.is_root_admin()) with check(public.is_root_admin());

-- Catálogos e inventario.
drop policy if exists families_admin_select on public.asset_families; drop policy if exists families_admin_insert on public.asset_families; drop policy if exists families_admin_update on public.asset_families;
create policy families_permission_select on public.asset_families for select to authenticated using(public.has_permission('inventory.view')); create policy families_root_insert on public.asset_families for insert to authenticated with check(public.is_root_admin()); create policy families_root_update on public.asset_families for update to authenticated using(public.is_root_admin()) with check(public.is_root_admin());
drop policy if exists statuses_admin_select on public.asset_statuses; drop policy if exists statuses_admin_insert on public.asset_statuses; drop policy if exists statuses_admin_update on public.asset_statuses;
create policy statuses_permission_select on public.asset_statuses for select to authenticated using(public.has_permission('inventory.view')); create policy statuses_root_insert on public.asset_statuses for insert to authenticated with check(public.is_root_admin()); create policy statuses_root_update on public.asset_statuses for update to authenticated using(public.is_root_admin()) with check(public.is_root_admin());
drop policy if exists locations_admin_select on public.locations; drop policy if exists locations_admin_insert on public.locations; drop policy if exists locations_admin_update on public.locations;
create policy locations_permission_select on public.locations for select to authenticated using(public.has_permission('locations.view') or public.has_permission('inventory.view')); create policy locations_permission_insert on public.locations for insert to authenticated with check(public.has_permission('locations.manage')); create policy locations_permission_update on public.locations for update to authenticated using(public.has_permission('locations.manage')) with check(public.has_permission('locations.manage'));
drop policy if exists assets_admin_select on public.assets; drop policy if exists assets_admin_insert on public.assets; drop policy if exists assets_admin_update on public.assets;
create policy assets_permission_select on public.assets for select to authenticated using(public.has_permission('inventory.view')); create policy assets_permission_insert on public.assets for insert to authenticated with check(public.has_permission('inventory.create')); create policy assets_permission_update on public.assets for update to authenticated using(public.has_permission('inventory.edit') or public.has_permission('inventory.dispose') or public.has_permission('inventory.reactivate')) with check(public.has_permission('inventory.edit') or public.has_permission('inventory.dispose') or public.has_permission('inventory.reactivate'));

-- Detalles especializados.
drop policy if exists computer_admin_select on public.computer_details; drop policy if exists computer_admin_insert on public.computer_details; drop policy if exists computer_admin_update on public.computer_details;
create policy computer_permission_select on public.computer_details for select to authenticated using(public.has_permission('inventory.view')); create policy computer_permission_insert on public.computer_details for insert to authenticated with check(public.has_permission('inventory.create')); create policy computer_permission_update on public.computer_details for update to authenticated using(public.has_permission('inventory.edit')) with check(public.has_permission('inventory.edit'));
drop policy if exists projector_admin_select on public.projector_details; drop policy if exists projector_admin_insert on public.projector_details; drop policy if exists projector_admin_update on public.projector_details;
create policy projector_permission_select on public.projector_details for select to authenticated using(public.has_permission('inventory.view')); create policy projector_permission_insert on public.projector_details for insert to authenticated with check(public.has_permission('inventory.create')); create policy projector_permission_update on public.projector_details for update to authenticated using(public.has_permission('inventory.edit')) with check(public.has_permission('inventory.edit'));
drop policy if exists television_admin_select on public.television_details; drop policy if exists television_admin_insert on public.television_details; drop policy if exists television_admin_update on public.television_details;
create policy television_permission_select on public.television_details for select to authenticated using(public.has_permission('inventory.view')); create policy television_permission_insert on public.television_details for insert to authenticated with check(public.has_permission('inventory.create')); create policy television_permission_update on public.television_details for update to authenticated using(public.has_permission('inventory.edit')) with check(public.has_permission('inventory.edit'));

-- Historial, bajas, migraciones y auditoría.
drop policy if exists history_admin_select on public.asset_history; drop policy if exists history_admin_insert on public.asset_history;
create policy history_permission_select on public.asset_history for select to authenticated using(public.has_permission('inventory.view') or public.has_permission('audit.view'));
create policy history_permission_insert on public.asset_history for insert to authenticated with check(actor_id=(select auth.uid()) and ((event_type='created' and public.has_permission('inventory.create')) or (event_type='updated' and public.has_permission('inventory.edit')) or (event_type='disposed' and public.has_permission('inventory.dispose')) or (event_type='reactivated' and public.has_permission('inventory.reactivate')) or public.is_root_admin()));
drop policy if exists disposals_admin_select on public.asset_disposals; drop policy if exists disposals_admin_insert on public.asset_disposals; drop policy if exists disposals_admin_update on public.asset_disposals;
create policy disposals_permission_select on public.asset_disposals for select to authenticated using(public.has_permission('inventory.view')); create policy disposals_permission_insert on public.asset_disposals for insert to authenticated with check(created_by=(select auth.uid()) and public.has_permission('inventory.dispose')); create policy disposals_root_update on public.asset_disposals for update to authenticated using(public.is_root_admin()) with check(public.is_root_admin());
drop policy if exists legacy_admin_select on public.legacy_imports; drop policy if exists legacy_admin_insert on public.legacy_imports; drop policy if exists legacy_admin_update on public.legacy_imports;
create policy legacy_permission_select on public.legacy_imports for select to authenticated using(public.has_permission('imports.view')); create policy legacy_permission_insert on public.legacy_imports for insert to authenticated with check(public.has_permission('imports.manage')); create policy legacy_permission_update on public.legacy_imports for update to authenticated using(public.has_permission('imports.manage')) with check(public.has_permission('imports.manage'));
drop policy if exists migration_runs_admin_select on public.migration_runs; drop policy if exists migration_runs_admin_insert on public.migration_runs; drop policy if exists migration_runs_admin_update on public.migration_runs;
create policy migration_runs_permission_select on public.migration_runs for select to authenticated using(public.has_permission('imports.view')); create policy migration_runs_permission_insert on public.migration_runs for insert to authenticated with check(public.has_permission('imports.manage')); create policy migration_runs_permission_update on public.migration_runs for update to authenticated using(public.has_permission('imports.manage')) with check(public.has_permission('imports.manage'));
drop policy if exists audit_admin_select on public.audit_logs; drop policy if exists audit_admin_insert on public.audit_logs; revoke insert on public.audit_logs from authenticated; create policy audit_permission_select on public.audit_logs for select to authenticated using(public.has_permission('audit.view'));

-- Funciones atómicas existentes pasan a validar permisos RBAC.
create or replace function public.create_asset_atomic(p_asset jsonb,p_details jsonb default '{}'::jsonb) returns uuid language plpgsql security invoker set search_path='' as $$
declare v_actor uuid:=auth.uid(); v_asset_id uuid; v_family_code text; v_after jsonb; v_family_id uuid; v_status_id uuid; v_location_id uuid; v_quantity integer;
begin if v_actor is null then raise exception 'Usuario no autenticado'; end if; if not public.has_permission('inventory.create') then raise exception 'Permiso inventory.create requerido'; end if; v_family_id:=nullif(p_asset->>'family_id','')::uuid; v_status_id:=nullif(p_asset->>'status_id','')::uuid; v_location_id:=nullif(p_asset->>'location_id','')::uuid; v_quantity:=greatest(coalesce(nullif(p_asset->>'quantity','')::integer,1),1); select f.code into v_family_code from public.asset_families f where f.id=v_family_id and f.active=true; if v_family_code is null then raise exception 'Familia tecnológica inválida'; end if; insert into public.assets(inventory_code,family_id,status_id,location_id,name,asset_type,brand,model,serial_number,quantity,area,observations,created_by,updated_by) values(nullif(btrim(p_asset->>'inventory_code'),''),v_family_id,v_status_id,v_location_id,nullif(btrim(p_asset->>'name'),''),nullif(btrim(p_asset->>'asset_type'),''),nullif(btrim(p_asset->>'brand'),''),nullif(btrim(p_asset->>'model'),''),nullif(btrim(p_asset->>'serial_number'),''),v_quantity,nullif(btrim(p_asset->>'area'),''),nullif(btrim(p_asset->>'observations'),''),v_actor,v_actor) returning id into v_asset_id; if v_family_code='computer' then insert into public.computer_details(asset_id,memory,storage,screen,keyboard,battery,charger) values(v_asset_id,nullif(btrim(p_details->>'memory'),''),nullif(btrim(p_details->>'storage'),''),nullif(btrim(p_details->>'screen'),''),nullif(btrim(p_details->>'keyboard'),''),nullif(btrim(p_details->>'battery'),''),nullif(btrim(p_details->>'charger'),'')); elsif v_family_code='projector' then insert into public.projector_details(asset_id,lumens,hdmi,vga) values(v_asset_id,nullif(btrim(p_details->>'lumens'),''),nullif(btrim(p_details->>'hdmi'),''),nullif(btrim(p_details->>'vga'),'')); elsif v_family_code='television' then insert into public.television_details(asset_id,size) values(v_asset_id,nullif(btrim(p_details->>'size'),'')); end if; select to_jsonb(a) into v_after from public.assets a where a.id=v_asset_id; insert into public.asset_history(asset_id,event_type,description,after_data,actor_id) values(v_asset_id,'created','Activo creado desde la aplicación web.',v_after,v_actor); return v_asset_id; end;$$;

-- Las demás funciones mantienen su lógica transaccional y sustituyen admin hardcodeado por has_permission.
-- Se recrean para evitar divergencia entre producción y un entorno limpio.
create or replace function public.update_asset_atomic(p_asset_id uuid,p_asset jsonb,p_details jsonb default '{}'::jsonb) returns void language plpgsql security invoker set search_path='' as $$
declare v_actor uuid:=auth.uid(); v_before jsonb; v_after jsonb; v_family_id uuid; v_family_code text; v_status_id uuid; v_location_id uuid; v_quantity integer;
begin if v_actor is null then raise exception 'Usuario no autenticado'; end if; if not public.has_permission('inventory.edit') then raise exception 'Permiso inventory.edit requerido'; end if; select to_jsonb(a),a.family_id into v_before,v_family_id from public.assets a where a.id=p_asset_id for update; if v_before is null then raise exception 'Activo no encontrado'; end if; select f.code into v_family_code from public.asset_families f where f.id=v_family_id; v_status_id:=nullif(p_asset->>'status_id','')::uuid; v_location_id:=nullif(p_asset->>'location_id','')::uuid; v_quantity:=greatest(coalesce(nullif(p_asset->>'quantity','')::integer,1),1); update public.assets set inventory_code=nullif(btrim(p_asset->>'inventory_code'),''),status_id=v_status_id,location_id=v_location_id,name=nullif(btrim(p_asset->>'name'),''),asset_type=nullif(btrim(p_asset->>'asset_type'),''),brand=nullif(btrim(p_asset->>'brand'),''),model=nullif(btrim(p_asset->>'model'),''),serial_number=nullif(btrim(p_asset->>'serial_number'),''),quantity=v_quantity,area=nullif(btrim(p_asset->>'area'),''),observations=nullif(btrim(p_asset->>'observations'),''),updated_by=v_actor where id=p_asset_id; if v_family_code='computer' then insert into public.computer_details(asset_id,memory,storage,screen,keyboard,battery,charger) values(p_asset_id,nullif(btrim(p_details->>'memory'),''),nullif(btrim(p_details->>'storage'),''),nullif(btrim(p_details->>'screen'),''),nullif(btrim(p_details->>'keyboard'),''),nullif(btrim(p_details->>'battery'),''),nullif(btrim(p_details->>'charger'),'')) on conflict(asset_id) do update set memory=excluded.memory,storage=excluded.storage,screen=excluded.screen,keyboard=excluded.keyboard,battery=excluded.battery,charger=excluded.charger; elsif v_family_code='projector' then insert into public.projector_details(asset_id,lumens,hdmi,vga) values(p_asset_id,nullif(btrim(p_details->>'lumens'),''),nullif(btrim(p_details->>'hdmi'),''),nullif(btrim(p_details->>'vga'),'')) on conflict(asset_id) do update set lumens=excluded.lumens,hdmi=excluded.hdmi,vga=excluded.vga; elsif v_family_code='television' then insert into public.television_details(asset_id,size) values(p_asset_id,nullif(btrim(p_details->>'size'),'')) on conflict(asset_id) do update set size=excluded.size; end if; select to_jsonb(a) into v_after from public.assets a where a.id=p_asset_id; insert into public.asset_history(asset_id,event_type,description,before_data,after_data,actor_id) values(p_asset_id,'updated','Activo actualizado desde la aplicación web.',v_before,v_after,v_actor); end;$$;
create or replace function public.dispose_asset_atomic(p_asset_id uuid,p_reason text,p_observations text default null,p_approved_by text default null) returns void language plpgsql security invoker set search_path='' as $$
declare v_actor uuid:=auth.uid(); v_status_id uuid; v_before jsonb; v_after jsonb; v_is_disposed boolean; begin if v_actor is null then raise exception 'Usuario no autenticado'; end if; if not public.has_permission('inventory.dispose') then raise exception 'Permiso inventory.dispose requerido'; end if; select to_jsonb(a),a.is_disposed into v_before,v_is_disposed from public.assets a where a.id=p_asset_id for update; if v_before is null then raise exception 'Activo no encontrado'; end if; if v_is_disposed then raise exception 'El activo ya está dado de baja'; end if; select s.id into v_status_id from public.asset_statuses s where s.code='disposed' and s.active=true limit 1; update public.assets set is_disposed=true,status_id=v_status_id,updated_by=v_actor where id=p_asset_id; select to_jsonb(a) into v_after from public.assets a where a.id=p_asset_id; insert into public.asset_disposals(asset_id,reason,observations,approved_by,created_by) values(p_asset_id,nullif(btrim(p_reason),''),nullif(btrim(p_observations),''),nullif(btrim(p_approved_by),''),v_actor); insert into public.asset_history(asset_id,event_type,description,before_data,after_data,actor_id) values(p_asset_id,'disposed',coalesce(nullif(btrim(p_reason),''),'Activo dado de baja.'),v_before,v_after,v_actor); end;$$;
create or replace function public.reactivate_asset_atomic(p_asset_id uuid,p_reason text) returns void language plpgsql security invoker set search_path='' as $$
declare v_actor uuid:=auth.uid(); v_status_id uuid; v_before jsonb; v_after jsonb; v_is_disposed boolean; begin if v_actor is null then raise exception 'Usuario no autenticado'; end if; if not public.has_permission('inventory.reactivate') then raise exception 'Permiso inventory.reactivate requerido'; end if; select to_jsonb(a),a.is_disposed into v_before,v_is_disposed from public.assets a where a.id=p_asset_id for update; if v_before is null then raise exception 'Activo no encontrado'; end if; if not v_is_disposed then raise exception 'El activo no está dado de baja'; end if; select s.id into v_status_id from public.asset_statuses s where s.code='operational' and s.active=true limit 1; update public.assets set is_disposed=false,status_id=v_status_id,updated_by=v_actor where id=p_asset_id; select to_jsonb(a) into v_after from public.assets a where a.id=p_asset_id; insert into public.asset_history(asset_id,event_type,description,before_data,after_data,actor_id) values(p_asset_id,'reactivated','Reactivado: '||coalesce(nullif(btrim(p_reason),''),'sin detalle'),v_before,v_after,v_actor); end;$$;

revoke execute on function public.create_asset_atomic(jsonb,jsonb) from public,anon; revoke execute on function public.update_asset_atomic(uuid,jsonb,jsonb) from public,anon; revoke execute on function public.dispose_asset_atomic(uuid,text,text,text) from public,anon; revoke execute on function public.reactivate_asset_atomic(uuid,text) from public,anon;
grant execute on function public.create_asset_atomic(jsonb,jsonb) to authenticated; grant execute on function public.update_asset_atomic(uuid,jsonb,jsonb) to authenticated; grant execute on function public.dispose_asset_atomic(uuid,text,text,text) to authenticated; grant execute on function public.reactivate_asset_atomic(uuid,text) to authenticated;

insert into public.user_roles(user_id,role_id,assigned_by) select u.id,r.id,u.id from auth.users u cross join public.app_roles r where lower(u.email)=lower('admin@colprovidencia.cl') and r.code='super_admin' on conflict do nothing;
